# JavaFx Tutoriais

Utilizando o VScode

## Vscode Extension Pack for Java

https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack


## Criar Projeto

- Pressione <kbd>F1</kbd> e selecione a opção `Java: Create Java Projetc...`
- Selecione a opção `Maven`
- Selecione a opção `More...`
- Digita `fxml`
- Selecione a opção `javafx-archetype-fxml org.openjfx`
- Selecione a opção `0.0.6`
- Digite o valor `br.edu.ifba.saj.ads.poo` 
- Digite o nome projeto (exemplo: `controle`)
- Selecione a pasta de destino
- ao ser perguntado pelo valor de `version` pode deixar o valor padrão (1.0-SNAPSHOT)
- ao ser perguntado por `Confirm properties configuration` pode deixar o valor padrão (Y)
- Selecione `Open` para abrir o projeto em uma nova janela no VSCode
- No terminal execute `mvn clean javafx:run`


## Gluon Scene Builder

Instalar o Scene Builder

[https://gluonhq.com/products/scene-builder/](https://gluonhq.com/products/scene-builder/)

ou com o scoop

```console
scoop bucket add extras
scoop install extras/scene-builder
```


## SceneBuilder extension for Visual Studio Code

https://marketplace.visualstudio.com/items?itemName=bilalekrem.scenebuilderextension


### Configure Scene Builder path

Pressione <kbd>F1</kbd> e selecione a opção `Configure Scene Builde path`

### Abrir FXML arquivo

Clique com o lado direita do mouse e escolha a opção `Open in Scene Builder`



## Maven

O meven é uma ferramenta de automação de compilação usada principalmente em projetos Java. Ele ajuda a gerenciar dependências, compilar código, executar testes e empacotar aplicativos.

Como o javafx não faz mais parte do JDK, precisamos do maven para adicionar as dependências do JavaFX ao nosso projeto.

O maven usa um arquivo chamado `pom.xml` para gerenciar as dependências do projeto. No projeto gerado, o arquivo `pom.xml` já contém as dependências necessárias para o JavaFX.

Para executar o projeto com o JavaFX, você pode usar o seguinte comando Maven:

```bash
mvn clean javafx:run
``` 



## JavaFX Login Page

<iframe width="560" height="315" src="https://www.youtube.com/embed/kdPyxR-fMv4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>


## YouTube PlayLists

- [JavaFx UI - Mahmoud Hamwi](https://www.youtube.com/playlist?list=PLJUowayj1-sjDKChv5Rg0OevX-BJWGGiR)
- [JavaFX - Channel Ai](https://www.youtube.com/playlist?list=PLargMG6XA8zBKfhSXB9O_Wvy2nFURCujv)

## Repositórios templates

- [Step 1](https://github.com/20261-ifba-saj-ads-poo/javafx-template-step1)


## JavaFX 

- https://openjfx.io/

## JavaFX tutorial

- https://www.javatpoint.com/javafx-tutorial
- [Spring boot + javafx](https://ivanqueiroz.dev/posts/2024/2024-01-27-conectando-o-poder-do-spring-boot-%C3%A0-experi%C3%AAncia-visual-do-javafx-um-guia-completo/)
- [Quarkus + JavaFX](https://docs.quarkiverse.io/quarkus-fx/dev/index.html)