```plantuml
@startuml
left to right direction
map "Especificação \nde uma conta" as conta{
}
map conta1{
  numero =>1
  cliente => Fulano
  saldo =>100
  limite =>0
}
map conta2{
  numero =>2
  cliente =>Beltrano
  saldo =>90
  limite =>10
}
map conta3{
  numero =>3
  cliente =>Cicrano
  saldo =>900
  limite =>0
}

conta --> conta1 : new
conta --> conta2 : new
conta --> conta3 : new
@enduml
```