# Exercício: Modelagem TV

[^Takenami]

1. Utilizando os conhecimentos de O.O.  construa um programa utilizando as informações abaixo. 

    Uma televisão possui as seguintes características:
    - tamanho de tela (em polegadas);
    - volume: de 1 a 10 iniciando em 5 (somente no construtor);
    - marca;
    - voltagem (220 e 110);
    - canal.

    A televisão pode realizar as seguintes ações:
    - ligar: ao ligar a televisão deve imprimir seu consumo. O consumo deve ser definido pela voltagem multiplicada pela quantidades de polegadas;
    - desligar;
    - aumentar e diminuir o volume;
    - subir e descer canal.

Desenhe o diagrama UML da classe TV e implemente o código em Java para construir 3 televisões diferentes, utilizando o construtor e os métodos definidos.





## Link para entrega

[Entrega](https://classroom.github.com/a/axOgMl_4)

::: {.callout-note title="@[code](./code/tv/TV.java)" collapse="true"}
@[code](./code/tv/Voltagem.java)

  @[code](./code/tv/Main.java)
:::


<!-- @include: ../../../includes/bib.md -->