# Exercício: Modelagem DVD

adaptado de [^Takenami]

1. Utilizando os conhecimentos de O.O. construa um programa utilizando as informações abaixo. As características de um Aparelho de DVD devem ser definidas de acordo com as informações a seguir. Ao ser criado o Aparelho de DVD inicialmente está desligado. Seu volume pode alterar de 1 a 5 sendo que o nível inicial é 2. É possível inserir um filme no Aparelho de DVD. O filme possui as seguintes caraterísticas: nome, categoria e duração.

   As seguintes operações podem ser realizadas pelo Aparelho de DVD:
   - ligar e desligar;
   - aumentar e diminuir volume;
   - inserir filme;
   - remover filme;
   - play e stop.

   O programa deve obedecer as seguintes regras:
   - Só é possível fazer qualquer uma destas operações se o Aparelho de DVD estiver ligado;
   - Só é possível dar play no Aparelho de DVD se existir algum filme inserido;
   - Só é possível inserir um Filme se não tiver um Filme ja dentro do Aparelho de DVD;
   - Só é possível dar stop se o Aparelho de DVD estiver em play;
   - Ao dar play deve aparecer o nome e a duração do filme que está sendo exibido.

1. Escreva o diagrama UML da classe Aparelho de DVD e implemente o código em Java para construir 1 Aparelho de DVD e 3 filmes diferentes, utilizando o construtor e os métodos definidos e inserir um filme no Aparelho de DVD.

## Link para entrega

[Entrega](https://classroom.github.com/a/37LscCdR)


<!-- @include: ../../../includes/bib.md -->