# Exercício Polimorfismo

adapitado de [^Takenami]

1. Criar uma classe abstrata chamada `Operacao` com o atributo `valor` do tipo `double` e um método abstrato chamado `operar()` que retornará um valor do tipo `double`.
1. Crie uma classe `Debito` e outra `Credito` que herda as caraterísticas de `Operacao.` O construtor de `Debito` e `Credito` deve receber o valor da operação e atribuir este valor a variável definida em `Operacao` (superclasse). Estas classes (`Debito` e `Credito`) devem ter um método `operar()` que deve ser programado de acordo com sua finalidade: `operar()` da classe `Debito` retorna o valor negativo pois a operação deve ser um debito enquanto a o método `operar()` de `Credito` retorna o valor positivo.
1. Criar a classe `Conta` com o atributo `saldo` do tipo `double` que inicia com 0. Esta classe possui um método `executarOperacao(Operacao opr)` que recebe um parâmetro do tipo `Operacao` que vai operar o saldo da conta correte (se for debito diminui, se for credito soma). Esta classe também possui o método `getSaldo()` que retorna o saldo do saldo atual.
1. Crie a classe `Correntista` com os seguintes atributos: `nome` (do tipo String) e `conta` (do tipo `Conta`). O construtor de `Correntista` deve receber seu nome. A classe deve ter 2 métodos: `public String getNome()` e `public Conta getConta().` Estes métodos retornam o nome e a conta respectivamente.
1. Crie a classe `Banco` como descrito no código abaixo:
    ```java
    public class Banco {
        private List<Correntista> correntistas;

        public Banco() {
            this.correntistas = new ArrayList();
        }

        public void addCorrentista(String nome){
            //...
        }

        public Correntista getCorrentista(String nome) {
            //...
        }

        public void debitar(String nomeCorrentista, double valor) {
            Debito d = new Debito(valor);
            getCorrentista(nomeCorrentista).getConta().executarOperacao(d);
        }

        public void creditar(String nomeCorrentista, double valor) {
            Credito c = new Credito(valor);
            getCorrentista(nomeCorrentista).getConta().executarOperacao(c);
        }

        public double getSaldo(String nomeCorrentista) {
            return getCorrentista(nomeCorrentista).getConta().getSaldo();
        }

        public void transferir(String nomeCorrentistaOrigem, String nomeCorrentistaDestino, double valor) {
            debitar(nomeCorrentistaOrigem, valor);
            creditar(nomeCorrentistaDestino, valor);
        }
    }
    ```

::: {.callout-note title="Código: Operacao.java" collapse="true"}
```java
// Operacao.java
public abstract class Operacao {
    private double valor;

    public Operacao(double valor) {
        this.valor = valor;
    }

    public abstract double operar();

    protected double getValor() {
        return valor;
    }
}
```
```java
// Credito.java
public class Credito extends Operacao {

    public Credito(double valor) {
        super(valor);
    }
    @Override
    public double operar() {
        return getValor();
    }    
}
```
```java
// Debito.java
public class Debito extends Operacao {

    public Debito(double valor) {
        super(valor);        
    }

    @Override
    public double operar() {
        return getValor()*-1;
    }    
}
```
```java
// Conta.java
class Conta{
    private double saldo;

    public Conta() {
        saldo = 0;
    }

    public void executarOperacao(Operacao opr){
        saldo+=opr.operar();
    }

    public double getSaldo() {
        return saldo;
    }
}
```
```java
// Correntista.java
public class Correntista {
    private String nome;
    private Conta conta;

    public Correntista(String nome) {
        this.nome = nome;
        this.conta = new Conta();
    }

    public String getNome() {
        return nome;
    }

    public Conta getConta() {
        return conta;
    }
}
```
```java
// Banco.java
import java.util.ArrayList;
import java.util.List;

public class Banco {
    private List<Correntista> correntistas;


    public Banco() {
        this.correntistas = new ArrayList();
    }

    public void addCorrentista(String nome){
        correntistas.add(new Correntista(nome));
    }

    public Correntista getCorrentista(String nome) {
        for (Correntista correntista : correntistas) {
            if (correntista.getNome().equals(nome)) {
                return correntista;
            }
        }
        return null;
    }

    public void debitar(String nomeCorrentista, double valor) {
        Debito d = new Debito(valor);
        getCorrentista(nomeCorrentista).getConta().executarOperacao(d);
    }

    public void creditar(String nomeCorrentista, double valor) {
        Credito c = new Credito(valor);
        getCorrentista(nomeCorrentista).getConta().executarOperacao(c);
    }

    public double getSaldo(String nomeCorrentista) {
        return getCorrentista(nomeCorrentista).getConta().getSaldo();
    }

    public void transferir(String nomeCorrentistaOrigem, String nomeCorrentistaDestino, double valor) {
        debitar(nomeCorrentistaOrigem, valor);
        creditar(nomeCorrentistaDestino, valor);
    }
}
```
```java
// TestaConta.java
public class TestaConta {
    public static void main(String[] args) {
        Banco itau = new Banco();
        String nomeCorrentista1 = "Leandro";
        itau.addCorrentista(nomeCorrentista1);
        System.out.println("Saldo da conta de "+nomeCorrentista1+" :"+itau.getSaldo(nomeCorrentista1));
        itau.creditar(nomeCorrentista1, 500);
        System.out.println("Saldo da conta de "+nomeCorrentista1+" :"+itau.getSaldo(nomeCorrentista1));
        itau.debitar(nomeCorrentista1, 400);
        System.out.println("Saldo da conta de "+nomeCorrentista1+" :"+itau.getSaldo(nomeCorrentista1));
        String nomeCorrentista2 = "Leo";
        itau.addCorrentista(nomeCorrentista2);
        System.out.println("Saldo da conta de "+nomeCorrentista2+" :"+itau.getSaldo(nomeCorrentista2));
        itau.transferir(nomeCorrentista1, nomeCorrentista2, 300);
        System.out.println("Saldo da conta de "+nomeCorrentista1+" :"+itau.getSaldo(nomeCorrentista1));
        System.out.println("Saldo da conta de "+nomeCorrentista2+" :"+itau.getSaldo(nomeCorrentista2));
    }
}
```
::: 


  
2. Modifique o método `transferir` da classe `Banco` para utilizar uma classe `Transferir` que herde de `Operacao`:

## Entrega

[Link](https://classroom.github.com/a/PyNkDJZz)


<!-- @include: ../../../includes/bib.md -->